name: CI Pipeline

on:
  push:
    branches:
      - main # Also trigger on commits to the main branch

  pull_request:
    branches:
      - main # Also trigger on pull requests to the main branch
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Install dependencies
        run: |
          go mod tidy
          go get -v ./...
      - name: Install the application
        run: go install ./...

      - name: Run tests
        run: go test -v ./... || exit 1

      # Slack Notification for Success
      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text:  "🚀 Test job completed successfully!* :tada:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

      # Slack Notification for Failure
      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text:  "❌ Test job failed for branch :x:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the application
        run: go build -v -o dist/main ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-build-artifact
          path: dist/main
          if-no-files-found: warn

      - name: Checking artifact
        run: |
          ls -la
          tree dist

      # Slack Notification for Success
      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "✅ Build job completed successfully for ${{ github.ref_name }}:tada:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

      # Slack Notification for Failure
      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "❌ Build job failed for branch ${{ github.ref_name }} :x:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

  docker_build_push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from VERSION file
        id: read_version
        run: |
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION | xargs)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION file not found!"
            exit 1
          fi

      - name: Build and push Docker image
        run: |
          docker build -t manisankardivi/new:${{ env.VERSION }} .

      - name: Push Docker Image (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker push manisankardivi/new:${{ env.VERSION }}

      # Slack Notification for Success
      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "✅ Docker job completed successfully ${{ github.ref_name }} :tada:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

      # Slack Notification for Failure
      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "❌ Docker job failed for branch: ${{ github.ref_name }} :x:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

  k8s-manifest-files_update:
    runs-on: ubuntu-latest
    needs: docker_build_push
    if: github.ref == 'refs/heads/main' # Only run this job if the branch is 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        run: |
          VERSION=$(cat VERSION)
          echo "Version extracted: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout Kubernetes repo
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/MANISANKARDIVI/k8s_repo.git
          cd k8s_repo
          sed -i "s|image: manisankardivi/new:.*|image: manisankardivi/new:$VERSION|" manifest.yaml
          echo "Image Section:"
          grep "image: manisankardivi/new:" manifest.yaml

      - name: Check for changes and commit if updated
        run: |
          cd k8s_repo
          git config --global user.email "manisankardiv@gmail.com"
          git config --global user.name "manisankardivi"
          git add .
          if git diff --cached --exit-code --quiet; then
            echo "No changes detected in manifest.yaml. Skipping commit and branch creation."
            echo "SKIP_BRANCH=true" >> $GITHUB_ENV
          else
            echo "Changes detected. Committing changes."
            git commit -m "Updated manifest.yaml with version $VERSION | GitHub Actions Pipeline"
            echo "SKIP_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Create and push new branch with version (if changes exist)
        if: env.SKIP_BRANCH == 'false' # Only run if changes exist
        run: |
          cd k8s_repo
          NEW_BRANCH="release-v$VERSION"
          git checkout -b "$NEW_BRANCH"
          git push origin "$NEW_BRANCH"
          echo "Branch $NEW_BRANCH created and pushed successfully."

      # Slack Notification for Success
      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "✅ Kubernetes manifest update completed successfully!* :tada:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

      # Slack Notification for Failure
      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "❌ k8s-manifest-files_update job failed for branch: ${{ github.ref_name }} :x:
            Build Number: ${{ github.run_number }}
            Workflow Number: ${{ github.run_id }}
            Commit: ${{ github.sha }}
            URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
