name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Also trigger on commits to the main branch
      - dev # Trigger on commits to the dev branch
      - feature/* # Trigger on commits to branches starting with 'feature/'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Install dependencies
        run: |
          go mod tidy
          go get -v ./...

      - name: Install the application
        run: go install ./...

      - name: Run tests
        run: go test -v ./... || exit 1

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the application
        run: go build -v -o dist/main ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-build-artifact
          path: dist/main
          if-no-files-found: warn

      - name: Checking artifact
        run: |
          ls -la
          tree dist

  docker_build_push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from VERSION file
        id: read_version
        run: |
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION | xargs)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION file not found!"
            exit 1
          fi

      - name: Build and push Docker image
        run: |
          docker build -t manisankardivi/new:${{ env.VERSION }}

      - name: Push Docker Image (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker push manisankardivi/new:${{ env.VERSION }}

  k8s-manifest-files_update:
    runs-on: ubuntu-latest
    needs: docker_build_push
    if: github.ref == 'refs/heads/main' # Only run this job if the branch is 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        run: |
          VERSION=$(cat VERSION)
          echo "Version extracted: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout Kubernetes repo
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/MANISANKARDIVI/k8s_repo.git
          cd k8s_repo

          sed -i "s|image: manisankardivi/new:.*|image: manisankardivi/new:$VERSION|" manifest.yaml

          echo "Image Section:"
          grep "image: manisankardivi/new:" manifest.yaml

      - name: Check for changes and commit if updated
        run: |
          cd k8s_repo
          git config --global user.email "manisankardivi@gmail.com"
          git config --global user.name "manisankardivi"

          git add manifest.yaml

          if git diff --cached --exit-code --quiet; then
            echo "Version Not Updated"
          else
            echo "Version Updated"
            git commit -m "Updated manifest.yaml with version $VERSION | GitHub Actions Pipeline"
            git push origin main
          fi
