name: Node.js CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/node.yml'
      - 'node-test/**'
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/node.yml'
      - 'node-test/**'

jobs:
  Code-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js with caching for dependencies
      - name: Set up Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      # Step 3: Install dependencies and build code
      - name: Install dependencies
        run: |
          cd node-test
          npm install

      - name: Build code
        run: |
          cd node-test
          npm run build

      # Step 4: Save the build output as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist # Replace 'dist/' with the correct output directory

  Docker-Build-Push:
    runs-on: ubuntu-latest
    needs: Code-Build

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Read version from VERSION file
        id: read_version
        run: |
          if [ -f node-test/VERSION ]; then
            VERSION=$(cat node-test/VERSION | xargs)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION file not found!"
            exit 1
          fi
      - name: Build and push Docker image
        run: |
          cd go-test
          docker build -t manisankardivi/node:${{ env.VERSION }} .
          docker push manisankardivi/node:${{ env.VERSION }}

